import './globals.scss'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import { getServerSession } from 'next-auth'
import { authOptions } from '../../pages/api/auth/[...nextauth]'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  // 세션(서버)에 저장 assessToken으로 로그인 유무를 판단하려면 node.js에서 사용한 firebase 대신 JWT를 사용해야 함
  let session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="ko">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
